# variable params
SaveDir : bin/
ReUse_dir : na
algorithm : EiM
num_processors : auto  # 'auto', or integer number

num_systems : 1
num_repetitions : 1


DE:
  mut : 0.8
  mut_scheme : best1  # rand1, rand2, best1, best2, rtb1
  crossp : 0.8
  popsize : 20
  epochs : 20
  batch_size : 0
  batch_scheme : none  # none, shuffle, window
  batch_window_size : 2
  data_oversample : 0  # 0=off, 1=on
  data_weighting : 0  # apply imbalance ratio as fit weight

  BreakOnZeroFit : 0
  BreakOnNcomp : na  # 'na' = 0 = no break, 300000

  # 2attr: c2DDS, d2DDS (1000 instances)
  training_data : d2DDS

  IntpScheme : pn_binary  # pn_binary, band_binary, band, HOW, clustering, Ridge, RidgeHOW, Kmean
  FitScheme : error  # error, BCE, PCAH, ComScore (from clust), KmeanDist, KmeanSpace
  Gbest_fit : raw # raw=Fitscheme, error
  SigmoidCorner : 1

  threshold : 0  # used for - thresh_binary Intpretation Scheme

  RidgedAlpha : cv  # 'cv' = use cross validation, else use a number.
  # For Vout that is similar, if alpha is too low (i.e 0) warnign is thrown
  RidgedIntercept : True

  pt_IntpScheme : pn_binary  # used for RCpt
  pt_FitScheme : PCAH  # used for RCpt
  pt_final_IntpScheme : RidgeHOW  # used for RCpt
  pt_final_FitScheme : error  # used for RCpt



  # Set whether to save data with extra attribute, and to plot
  SaveExtraAttribute : 0
  PlotExtraAttribute : 1
  UseCustom_NewAttributeData : 0
  NewAttrDataDir : na

  # # For EiM Interp only
  num_readout_nodes : 1  # 'na' used when the Vout are used directly, normally 1 for most schemes
  readout_scheme : none  # none, sigmoid, sigmoid_scale

  save_fitvit : 1  # save the fitness vs itteration graphs

## Set the network size & type
network:
  model : D_RN  # R_RN, D_RN, NL_RN, NSNL_RN, TD_RN, PWL_RN
  num_input : 2
  num_output : 3
  num_config : 5



genome:

  Config:
    active : 1

  Shuffle :
    active : 1
    scheme : none  # perm_crossp_model : none  # none, linear, box, quad, unity

  InWeight:
    active : 1
    scheme : random  # random, AddSub
    min : -1
    max : 1

  InBias:
    active : 0
    min : -2
    max : 2

  OutWeight:
    active : 1
    scheme : random  # random, AddSub
    min : -2
    max : 2

  OutBias:
    active : 0  # Bias per readout_node (or per op if num_readout_nodes='na')
    min : -10
    max : 10

  PulseWidth:
    active : 0
    min : 0.1 # ms
    max : 100 # ms

  BandNumber:
    active : 0
    max : defualt  # max_number_bands --> defualt makes NumBands=NumClasses
  BandClass:
    active : 0
  BandEdge:
    active : 0
    lims : 0
  BandWidth:
    active : 0

  HOWperm:
    active : 0



spice:
  Vmin : -5
  Vmax : 5

  max_r : 100  # in kOhms
  min_r : 10 # in kOhms
  R_array_in : 'na' # pass a RRN netowrk defining array in

  in_contact_R : 200  # Ohm
  op_contact_R : 0  # Ohm
  op_shunt_R : 70  # kOhm, or 'none'

  rand_dir : 1  # diode random direction toggle
  defualt_diode_dir : 1
  DefualtDiode : 1


  # # NL Material correlation factor, vaired between [-1,1] varies actual
  # covarience between its max/min
  corr : 0

  # # Used for uniform dist selection
  material_a_min :  33 # 3.0e+6
  material_a_max :  170
  material_b_min :  28
  material_b_max :  960

  # # Used for Normal Distr selection
  a_mean : 120
  b_mean : 560
  a_std : 448
  b_std : 270



  parallelC : 0  # add parallel capacitors between nodes
  ParallelCapLim : [0.1, 10]  # in uF
  shuntC : 0
  ShuntCapLim : [0.1, 10] # in uF

  sim_type : sim_dc  # sim_dc, sim_trans_pulse, sim_trans_wave
  pulse_Tp : 100
  pulse_TT : 4.5e-3
  trans_t_unit : 'm'
  rloc : 0.75  # percentage time though the pulse that the Vout are read

  NN_max_r : 1000  # in kOhms

  num_layers : 1  # if more then one layer is used
  NodesPerLayer : 3
  ConfigPerLayer : 1

mg:
  plotMG : 1
  plot_defualt : 0
  MG_vary_Vconfig : 0
  MG_vary_PermConfig : 0
  MG_vary_InWeight : 0
  MG_vary_InBias : 0
  MG_vary_OutWeight : 1
  MG_vary_OutputBias : 0

  MG_animation : 0  # evolution ani
  MG_VaryInWeightsAni : 0
  MG_VaryOutWeightsAni : 0
  MG_VaryLargeInWeightsAni : 0
  MG_VaryLargeOutWeightsAni : 0









 # fin
